---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cert-manager-sync-v1
  namespace: cert-manager
  labels:
    app: cert-manager-sync
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cert-manager-sync
      version: v1
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9090"
        prometheus.io/path: "/metrics"
      labels:
        app: cert-manager-sync
        version: v1
    spec:
      serviceAccountName: cert-manager-sync
      imagePullSecrets:
        - name: regcred
      containers:
        - image: robertlestak/cert-manager-sync:latest
          name: cert-manager-sync
          envFrom:
          - secretRef:
              name: cert-manager-sync
              optional: true
          ports:
          - containerPort: 9090
            name: http-metrics
          resources:
            limits:
              cpu: 500m
              memory: 500Mi
            requests:
              cpu: 500m
              memory: 500Mi
      tolerations:
        - key: "node.kubernetes.io/arch"
          operator: "Equal"
          value: "arm64"
          effect: "PreferNoSchedule"
